---
components:
  - name: scd30
    description: Driver for SCD30 CO₂ sensor
    group: air-quality
    groups: []
    code_owners: UncleRus
    depends:
      - i2cdev
      - log
      - esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
    licenses:
      - name: BSD-3-Clause
    copyrights:
      - author:
          name: UncleRus
        year: 2021
      - author:
          name: Sensirion
        year: 2021
      - author:
          name: nated0g
        year: 2021
